use crate::api::cma::CmaReport;
use js_sys::Array;
use wasm_bindgen::prelude::*;
use web_sys::{window, Blob, Document, Element, Url};

#[wasm_bindgen]
pub fn export_cma_to_pdf(cma_json: &str) -> Result<Vec<u8>, JsValue> {
    let cma: CmaReport = serde_json::from_str(cma_json)
        .map_err(|e| JsValue::from_str(&format!("JSON parse error: {}", e)))?;

    let html = generate_cma_html(&cma);
    Ok(html.into_bytes())
}

fn generate_cma_html(cma: &CmaReport) -> String {
    let price_low = cma
        .price_recommendation_low
        .map(|p| format!("${:.0}", p))
        .unwrap_or_else(|| "N/A".to_string());
    let price_mid = cma
        .price_recommendation_mid
        .map(|p| format!("${:.0}", p))
        .unwrap_or_else(|| "N/A".to_string());
    let price_high = cma
        .price_recommendation_high
        .map(|p| format!("${:.0}", p))
        .unwrap_or_else(|| "N/A".to_string());
    let confidence = format!("{}%", cma.confidence);
    let dom = cma
        .avg_days_on_market
        .map(|d| format!("{:.0} days", d))
        .unwrap_or_else(|| "N/A".to_string());
    let ltsr = cma
        .list_to_sale_ratio
        .map(|r| format!("{:.1}%", r))
        .unwrap_or_else(|| "N/A".to_string());
    let price_per_sqft = cma
        .price_per_sqft
        .map(|p| format!("${:.2}/sqft", p))
        .unwrap_or_else(|| "N/A".to_string());
    let market_conditions = if cma.market_hot { "Hot" } else { "Normal" };

    format!(
        r#"<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CMA Report - {subject_address}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #333; }}
        .header {{ text-align: center; margin-bottom: 30px; border-bottom: 2px solid #2563eb; padding-bottom: 20px; }}
        .header h1 {{ color: #2563eb; margin: 0; }}
        .header p {{ color: #666; margin: 5px 0; }}
        .price-range {{ background: #eff6ff; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }}
        .price-range h2 {{ margin: 0 0 10px; color: #1e40af; }}
        .price-range .prices {{ font-size: 24px; font-weight: bold; color: #2563eb; }}
        .metrics {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0; }}
        .metric {{ background: #f9fafb; padding: 15px; border-radius: 6px; }}
        .metric .label {{ font-size: 12px; color: #6b7280; text-transform: uppercase; }}
        .metric .value {{ font-size: 18px; font-weight: 600; color: #111827; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Comparative Market Analysis</h1>
        <p><strong>{subject_address}</strong></p>
        <p>Property Type: {property_type}</p>
        <p>MLS#: {mls_number}</p>
        <p>Report Date: {date}</p>
    </div>
    
    <div class="price-range">
        <h2>Recommended Price Range</h2>
        <div class="prices">{low} - {high}</div>
        <p style="margin-top: 10px;">Mid Point: <strong>{mid}</strong></p>
        <p>Confidence: {conf}</p>
    </div>
    
    <div class="metrics">
        <div class="metric">
            <div class="label">Avg Days on Market</div>
            <div class="value">{dom}</div>
        </div>
        <div class="metric">
            <div class="label">List-to-Sale Ratio</div>
            <div class="value">{ltsr}</div>
        </div>
        <div class="metric">
            <div class="label">Price per Sq Ft</div>
            <div class="value">{price_per_sqft}</div>
        </div>
        <div class="metric">
            <div class="label">Market Conditions</div>
            <div class="value">{market_conditions}</div>
        </div>
    </div>
    
    <div class="footer">
        <p>This CMA is provided for informational purposes only and should not be considered as financial or legal advice.</p>
        <p>Generated by WizAI Agent Dashboard</p>
    </div>
</body>
</html>"#,
        subject_address = cma.subject_address,
        property_type = cma.property_type,
        mls_number = cma.subject_mls_number.as_deref().unwrap_or("N/A"),
        date = chrono::Utc::now().format("%B %d, %Y"),
        low = price_low,
        mid = price_mid,
        high = price_high,
        conf = confidence,
        dom = dom,
        ltsr = ltsr,
        price_per_sqft = price_per_sqft,
        market_conditions = market_conditions,
    )
}

#[wasm_bindgen]
pub fn download_cma_pdf(cma_json: &str, filename: &str) -> Result<(), JsValue> {
    let html_bytes = export_cma_to_pdf(cma_json)?;

    let array = Array::new_with_length(html_bytes.len() as u32);
    for (i, byte) in html_bytes.iter().enumerate() {
        array.set(i as u32, JsValue::from_f64(*byte as f64));
    }

    let blob = Blob::new_with_array_buffer_view(&array)?;
    let url = Url::create_object_url_with_blob(&blob)?;

    let doc = window()
        .ok_or_else(|| JsValue::from_str("No window"))?
        .document()
        .ok_or_else(|| JsValue::from_str("No document"))?;

    let anchor: Element = doc.create_element("a")?;
    anchor.set_attribute("href", &url)?;
    anchor.set_attribute("download", filename)?;

    let body = doc.body().ok_or_else(|| JsValue::from_str("No body"))?;
    body.append_child(&anchor)?;
    anchor.dyn_ref::<web_sys::HtmlElement>()?.click();
    body.remove_child(&anchor)?;

    Url::revoke_object_url(&url)?;
    Ok(())
}
