//! Market research and CMA data models for AI Real Estate Team
//!
//! Defines structures for comparative market analysis, property data, and market reports

use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// Property type in the market
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PropertyCategory {
    Detached,
    SemiDetached,
    Townhouse,
    Condo,
    Commercial,
    MultiFamily,
    Land,
}

/// Status of a property listing
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ListingStatus {
    Active,
    Sold,
    Pending,
    Expired,
    Withdrawn,
    Leased,
}

/// Comparable property data
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComparableProperty {
    /// MLS number
    pub mls_number: String,
    /// Property address
    pub address: String,
    /// Property type
    pub property_type: PropertyCategory,
    /// Listing status
    pub status: ListingStatus,
    /// List price (if active) or sold price (if sold)
    pub price: f64,
    /// Original list price
    pub original_list_price: Option<f64>,
    /// Sale date (if sold)
    pub sold_date: Option<NaiveDate>,
    /// List date
    pub list_date: NaiveDate,
    /// Days on market
    pub days_on_market: i32,
    /// Bedrooms
    pub bedrooms: Option<f32>,
    /// Bathrooms
    pub bathrooms: Option<f32>,
    /// Square footage
    pub square_feet: Option<i32>,
    /// Lot size
    pub lot_size: Option<String>,
    /// Property features
    pub features: Vec<String>,
    /// Distance from subject property (km)
    pub distance_km: f64,
    /// Similarity score (0-100)
    pub similarity_score: i32,
    /// Data source
    pub source: String,
}

/// CMA Report for a subject property
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct CMAReport {
    /// Unique identifier
    pub id: String,
    /// Subject property address
    pub subject_address: String,
    /// Subject property MLS number (if known)
    pub subject_mls_number: Option<String>,
    /// Property type
    pub property_type: PropertyCategory,
    /// Report status
    pub status: CMAStatus,
    /// Generated by AI agent
    pub generated_by: String,
    /// Reviewed by human agent
    pub reviewed_by: Option<String>,
    /// When reviewed
    pub reviewed_at: Option<DateTime<Utc>>,
    /// Comparable properties (JSON array)
    pub comparables: serde_json::Value,
    /// Market analysis data (JSON)
    pub market_analysis: serde_json::Value,
    /// AI-generated summary
    pub summary: String,
    /// Price recommendation (low, mid, high)
    pub price_recommendation_low: Option<f64>,
    pub price_recommendation_mid: Option<f64>,
    pub price_recommendation_high: Option<f64>,
    /// Market conditions
    pub market_conditions: Option<String>,
    /// Days on market average
    pub avg_days_on_market: Option<f32>,
    /// Price per square foot
    pub price_per_sqft: Option<f64>,
    /// List to sale ratio
    pub list_to_sale_ratio: Option<f32>,
    /// Confidence level (0-100)
    pub confidence: i32,
    /// Creation timestamp
    pub created_at: DateTime<Utc>,
    /// Last update timestamp
    pub updated_at: DateTime<Utc>,
}

/// CMA report status
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(rename_all = "lowercase")]
pub enum CMAStatus {
    /// Draft, AI generated
    Draft,
    /// Under human review
    UnderReview,
    /// Human approved
    Approved,
    /// Human rejected
    Rejected,
    /// Archived
    Archived,
}

impl Default for CMAStatus {
    fn default() -> Self {
        CMAStatus::Draft
    }
}

impl CMAReport {
    /// Create a new CMA report
    pub fn new(
        subject_address: impl Into<String>,
        subject_mls: Option<impl Into<String>>,
        property_type: PropertyCategory,
        generated_by: impl Into<String>,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4().to_string(),
            subject_address: subject_address.into(),
            subject_mls_number: subject_mls.map(|m| m.into()),
            property_type,
            status: CMAStatus::Draft,
            generated_by: generated_by.into(),
            reviewed_by: None,
            reviewed_at: None,
            comparables: serde_json::json!([]),
            market_analysis: serde_json::json!({}),
            summary: String::new(),
            price_recommendation_low: None,
            price_recommendation_mid: None,
            price_recommendation_high: None,
            market_conditions: None,
            avg_days_on_market: None,
            price_per_sqft: None,
            list_to_sale_ratio: None,
            confidence: 0,
            created_at: now,
            updated_at: now,
        }
    }

    /// Add comparables to the report
    pub fn set_comparables(&mut self, comparables: Vec<ComparableProperty>) {
        self.comparables = serde_json::to_value(&comparables).unwrap_or_default();
        self.updated_at = Utc::now();
    }

    /// Set market analysis
    pub fn set_market_analysis(&mut self, analysis: MarketAnalysis) {
        self.market_analysis = serde_json::to_value(&analysis).unwrap_or_default();
        self.updated_at = Utc::now();
    }

    /// Set price recommendation
    pub fn set_price_recommendation(&mut self, low: f64, mid: f64, high: f64) {
        self.price_recommendation_low = Some(low);
        self.price_recommendation_mid = Some(mid);
        self.price_recommendation_high = Some(high);
        self.updated_at = Utc::now();
    }

    /// Mark as under review
    pub fn mark_under_review(&mut self) {
        self.status = CMAStatus::UnderReview;
        self.updated_at = Utc::now();
    }

    /// Approve the report
    pub fn approve(&mut self, reviewer: impl Into<String>) {
        self.status = CMAStatus::Approved;
        self.reviewed_by = Some(reviewer.into());
        self.reviewed_at = Some(Utc::now());
        self.updated_at = Utc::now();
    }

    /// Reject the report
    pub fn reject(&mut self, reviewer: impl Into<String>) {
        self.status = CMAStatus::Rejected;
        self.reviewed_by = Some(reviewer.into());
        self.reviewed_at = Some(Utc::now());
        self.updated_at = Utc::now();
    }

    /// Get comparables as typed Vec
    pub fn get_comparables(&self) -> Vec<ComparableProperty> {
        serde_json::from_value(self.comparables.clone()).unwrap_or_default()
    }

    /// Get market analysis
    pub fn get_market_analysis(&self) -> Option<MarketAnalysis> {
        serde_json::from_value(self.market_analysis.clone()).ok()
    }
}

/// Market analysis data
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketAnalysis {
    /// Geographic area analyzed
    pub area: String,
    /// Analysis period start
    pub period_start: NaiveDate,
    /// Analysis period end
    pub period_end: NaiveDate,
    /// Total active listings
    pub active_listings: i32,
    /// Total sold in period
    pub sold_count: i32,
    /// Average list price
    pub avg_list_price: f64,
    /// Average sold price
    pub avg_sold_price: f64,
    /// Median sold price
    pub median_sold_price: f64,
    /// Average days on market
    pub avg_days_on_market: f32,
    /// Price per square foot average
    pub avg_price_per_sqft: f64,
    /// Inventory months supply
    pub months_of_inventory: f32,
    /// List to sale ratio
    pub list_to_sale_ratio: f32,
    /// Market trend direction
    pub trend_direction: TrendDirection,
    /// Market conditions description
    pub conditions_description: String,
}

/// Market trend direction
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TrendDirection {
    StronglyUp,
    SlightlyUp,
    Stable,
    SlightlyDown,
    StronglyDown,
}

/// Market report for a geographic area
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct MarketReport {
    /// Unique identifier
    pub id: String,
    /// Geographic area
    pub area: String,
    /// Property types included
    pub property_types: serde_json::Value,
    /// Report period
    pub period_start: NaiveDate,
    pub period_end: NaiveDate,
    /// Generated by AI
    pub generated_by: String,
    /// Market analysis data (JSON)
    pub analysis_data: serde_json::Value,
    /// Generated summary
    pub summary: String,
    /// Key findings
    pub key_findings: serde_json::Value,
    /// Recommendations
    pub recommendations: serde_json::Value,
    /// Data sources
    pub data_sources: serde_json::Value,
    /// Confidence level
    pub confidence: i32,
    /// Creation timestamp
    pub created_at: DateTime<Utc>,
}

impl MarketReport {
    /// Create new market report
    pub fn new(
        area: impl Into<String>,
        period_start: NaiveDate,
        period_end: NaiveDate,
        generated_by: impl Into<String>,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            area: area.into(),
            property_types: serde_json::json!([]),
            period_start,
            period_end,
            generated_by: generated_by.into(),
            analysis_data: serde_json::json!({}),
            summary: String::new(),
            key_findings: serde_json::json!([]),
            recommendations: serde_json::json!([]),
            data_sources: serde_json::json!([]),
            confidence: 0,
            created_at: Utc::now(),
        }
    }
}

/// Property search criteria
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PropertySearchCriteria {
    /// Location (city, neighborhood, postal code)
    pub location: String,
    /// Property types
    pub property_types: Vec<PropertyCategory>,
    /// Price range min
    pub price_min: Option<f64>,
    /// Price range max
    pub price_max: Option<f64>,
    /// Bedrooms min
    pub bedrooms_min: Option<f32>,
    /// Bedrooms max
    pub bedrooms_max: Option<f32>,
    /// Bathrooms min
    pub bathrooms_min: Option<f32>,
    /// Square footage min
    pub sqft_min: Option<i32>,
    /// Square footage max
    pub sqft_max: Option<i32>,
    /// Status
    pub status: Option<ListingStatus>,
    /// Search radius (km)
    pub radius_km: Option<f64>,
    /// Minimum sold date (for comparables)
    pub min_sold_date: Option<NaiveDate>,
}

/// Request to generate a CMA
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateCMARequest {
    pub subject_address: String,
    pub subject_mls_number: Option<String>,
    pub property_type: PropertyCategory,
    pub property_details: Option<PropertyDetails>,
}

/// Property details for CMA
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PropertyDetails {
    pub bedrooms: Option<f32>,
    pub bathrooms: Option<f32>,
    pub square_feet: Option<i32>,
    pub lot_size: Option<String>,
    pub year_built: Option<i32>,
    pub features: Vec<String>,
}

/// Request to search comparables
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchComparablesRequest {
    pub address: String,
    pub mls_number: Option<String>,
    pub property_type: PropertyCategory,
    pub radius_km: f64,
    pub price_range_percent: Option<f64>,
    pub max_results: Option<i32>,
}

/// CMA summary for list view
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CMASummary {
    pub id: String,
    pub subject_address: String,
    pub property_type: PropertyCategory,
    pub status: CMAStatus,
    pub price_recommendation_mid: Option<f64>,
    pub comparable_count: i32,
    pub confidence: i32,
    pub created_at: DateTime<Utc>,
}

/// Market trend data point
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrendDataPoint {
    pub date: NaiveDate,
    pub avg_price: f64,
    pub median_price: f64,
    pub sales_count: i32,
    pub new_listings: i32,
    pub inventory: i32,
    pub days_on_market: f32,
}

/// Market sentiment data
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketSentiment {
    pub location: String,
    pub overall_sentiment: String,
    pub sentiment_score: f32, // -1.0 to 1.0
    pub key_indicators: Vec<SentimentIndicator>,
    pub news_sources: Vec<String>,
    pub last_updated: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SentimentIndicator {
    pub name: String,
    pub value: String,
    pub trend: String,
    pub impact: String,
}

/// Buyer preference profile
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuyerProfile {
    pub id: String,
    pub lead_id: String,
    pub must_have_features: Vec<String>,
    pub nice_to_have_features: Vec<String>,
    pub deal_breakers: Vec<String>,
    pub preferred_locations: Vec<String>,
    pub budget_min: Option<f64>,
    pub budget_max: Option<f64>,
    pub timeline: String,
    pub property_types: Vec<PropertyCategory>,
    pub notes: String,
}

/// Property comparison result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PropertyComparison {
    pub property_id: String,
    pub address: String,
    pub price: f64,
    pub score: i32, // 0-100 match score
    pub pros: Vec<String>,
    pub cons: Vec<String>,
    pub notes: String,
}
